### ISSUE TITLE
Headers need to be responsive and items need to align properly 

### ISSUE THREAD

**Issue by kapilG0** [BamaCharanChhandogi/READMEasy#1]
![Screenshot_20241001_223322](https://github.com/user-attachments/assets/bbad4b2b-4681-4b21-b16c-6b23d73cc374)

**Comment by kapilG0** [comment]
Hello @BamaCharanChhandogi please assign this issue to me under gssoc 24

**Comment by BamaCharanChhandogi** [comment]
This issue is already working by someone. please free feel to raise any other issue. I am closing this issue right now.
