### ISSUE TITLE
[Feature]: Markdown Editor For Github Profile Fetcher by URL

### ISSUE THREAD

**Issue by ParasY1724** [BamaCharanChhandogi/READMEasy#103]
# 🚀 Feature Request

### 📝 Feature Description
Introduce a feature that allows users to input any GitHub profile URL to fetch the profile's template. A markdown editor will be provided with a side-by-side live preview, enabling users to edit and see changes in real-time.

### 🔧 How Will This Enhance the App?
If a user admires someone's GitHub profile but finds editing raw markdown difficult, providing a markdown editor alongside live rendering will greatly improve the user experience. This feature allows users to make edits and compare changes in real-time, making the process more intuitive and efficient.

**Comment by ParasY1724** [comment]
Please assign this task to me

**Comment by BamaCharanChhandogi** [comment]
Users can easily render in GitHub.we do not need this feature.
