### ISSUE TITLE
Add New Feature: Generate Requirment.txt file.

### ISSUE THREAD

**Issue by Jay-1409** [BamaCharanChhandogi/READMEasy#11]
The idea of generating readme files using Gemini API was excellent. I got an idea: to help create the Requirment.txt file using REST API Github to fetch the dependencies and make a file out of it.

We can add this as a new feature.

If you like this idea, please assign it to me under Gssoc 2024 Extd.
Thank you !!

**Comment by BamaCharanChhandogi** [comment]
Hi @Jay-1409, the `Requirment.txt` file is for the Python project right, and this is the `react` base, so why do we add it here?

**Comment by Jay-1409** [comment]
I meant this as a feature to be added to the website.

**Comment by BamaCharanChhandogi** [comment]
This site is basically for GitHub readme or profile related, if you have any other ideas related to this feel free to discuss.I am closing  this issue now.
