### ISSUE TITLE
[Feature]: Add a footer section to make website more professsional.

### ISSUE THREAD

**Issue by rishika105** [BamaCharanChhandogi/READMEasy#118]
### 📝 **Feature Description**
I would like to add an enhanced footer with social media icons, quick links, and contact details to improve user navigation and engagement.

### 🔧 **How Will This Enhance the App?**
This will provide better navigation, increase professionalism, and allow users to quickly access important pages and social media links, improving the user experience.

### 🎯 **Use Cases**
1. Users can easily navigate to social media platforms.
2. Quick access to links such as Privacy Policy, My Account, etc.
3. Improved branding with a modern, consistent footer design.

### 📦 **Suggested Implementation**
- Add sections for:
  1. **Quick Links** (About Us, Support, My Account)
  2. **Social Media Icons** (Facebook, Twitter, Instagram, LinkedIn, GitHub)
  3. **Contact Information** (email, phone number)

**Comment by BamaCharanChhandogi** [comment]
Do not need
