### ISSUE TITLE
I would like to propose an enhancement to the navbar component to improve its responsiveness across various screen sizes.

### ISSUE THREAD

**Issue by prajwaln07** [BamaCharanChhandogi/READMEasy#13]
The current navbar layout does not adapt well to smaller screens, making it difficult for users to navigate the application effectively.

Proposed Solution:

We have built a separate responsive navbar component that adjusts its layout based on the screen size. This implementation includes a hamburger menu for mobile views, ensuring that all navigation links remain accessible.

Before and After:

# Before Implementation:

![readmeeasy](https://github.com/user-attachments/assets/18985f36-ae42-4c6f-bf26-7faba0e9882a)

# After Implementation:

![readmeasyup0](https://github.com/user-attachments/assets/0a860597-ccc6-4973-a56c-79dfcd2bc7fa)
![Readmeasyup1](https://github.com/user-attachments/assets/a68287ea-469d-43d7-bc94-a6746cc38aeb)

Benefits:

Enhanced user experience on mobile devices
Improved accessibility for all users
Maintains aesthetic consistency with the existing design
I look forward to your feedback and approval to proceed with this enhancement!
@BamaCharanChhandogi

**Comment by prajwaln07** [comment]
@BamaCharanChhandogi  can you assign it to me

**Comment by Raj-Aditya-27** [comment]
Hi @BamaCharanChhandogi 
I can see that navbar is still not responsive upto the mark.
Please assign me this issue.
I will do my best and raise a PR request shortly.

**Comment by itznayan** [comment]
hey @BamaCharanChhandogi please assign this issue to me.

**Comment by BamaCharanChhandogi** [comment]
@prajwaln07 are you working on this issue?

**Comment by itznayan** [comment]
@BamaCharanChhandogi can you please assign this issue to me.

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi can you please assign this issue to me?

Hi @itznayan, if I don't get a response from @prajwaln07, I will assign the task to you.

**Comment by prajwaln07** [comment]
@BamaCharanChhandogi i have already  raised a PR. Please check it
