### ISSUE TITLE
# Add Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by AnujShrivastava01** [BamaCharanChhandogi/READMEasy#15]
I would like to propose implementing a dark/light mode toggle for the website. This feature will enhance user experience by allowing users to switch between themes based on their preferences.
Proposed changes:
1.	Add a toggle switch in the UI for users to switch between dark and light modes.
2.	Ensure that all elements of the website adapt to the selected theme.
3.	Save user preferences using local storage so the selected mode persists across sessions.
Could you please assign this issue to me? 
Thank you!

**Comment by BamaCharanChhandogi** [comment]
#8 duplicate

**Comment by mrpeace07** [comment]
i want to make changes and add dark and light mode if u can please assign this task to me ill start wortking on it

**Comment by Aditijainnn** [comment]
@BamaCharanChhandogi can i work on this?

**Comment by BamaCharanChhandogi** [comment]
duplicate
