### ISSUE TITLE
Add Toggle Functionality for Markdown and Rendered View in GitHubProfileGenerator Component

### ISSUE THREAD

**Issue by prajwaln07** [BamaCharanChhandogi/READMEasy#18]
We need to add a toggle feature in the GitHubProfileGenerator to switch between Markdown and rendered views of the generated README. This functionality is similar to what we have in the OutputDisplay component on the Home page.
@BamaCharanChhandogi can you assing this issue to me ?

**Comment by prajwaln07** [comment]
@BamaCharanChhandogi please assign me this issue under GSSoC and hacktoberfest

**before :**

![Screenshot (73)](https://github.com/user-attachments/assets/053a4af1-df88-4be1-8d4a-fbab4dd49f24)

**after :** 

![Screenshot (72)](https://github.com/user-attachments/assets/b00dfbde-c5b6-4a2f-9f19-b084acd866e6)
![Screenshot (71)](https://github.com/user-attachments/assets/a5213e34-633b-48a1-847a-71a8f4dcdaa8)

**Comment by prajwaln07** [comment]
@BamaCharanChhandogi  what do you think about this?

**Comment by prajwaln07** [comment]
please reply @BamaCharanChhandogi

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi what do you think about this?

Thanks for raising this . You can proceed.

**Comment by prajwaln07** [comment]
Hi @BamaCharanChhandogi , thanks for your earlier feedback and for assigning me the issue. I noticed that it was later closed as 'not planned.' Could you please share a bit more about why it was closed? I’d like to understand the project's direction better and ensure that my contributions align with the overall goals. If there's a way I can adapt the feature or work on something else that would be more useful, I'd be happy to adjust. Thanks for your guidance!

**Comment by BamaCharanChhandogi** [comment]
> Hi @BamaCharanChhandogi , thanks for your earlier feedback and for assigning me the issue. I noticed that it was later closed as 'not planned.' Could you please share a bit more about why it was closed? I’d like to understand the project's direction better and ensure that my contributions align with the overall goals. If there's a way I can adapt the feature or work on something else that would be more useful, I'd be happy to adjust. Thanks for your guidance!

Hello @prajwaln07, 
First of all thanks for your contributions. Actually, this feature has already been implemented here #63. This feature was added additionally. So we don't need the same feature. that's why I closed.

**Comment by prajwaln07** [comment]
@BamaCharanChhandogi  okay thanks for clarification.
