### ISSUE TITLE
Enhance README Clarity and Contribution Guidelines

### ISSUE THREAD

**Issue by prajwaln07** [BamaCharanChhandogi/READMEasy#25]
# The current README for READMEasy lacks clarity and essential details for users and contributors.

## Issues:

* No clear installation instructions for developers.
* Missing detailed contribution guidelines.
## Proposed Solution:
* Update the README to include:

## Step-by-step installation and setup instructions.
* Clear contribution process, including forking and raising pull requests.
## Action:
* Review and merge the updated README to improve documentation.

@BamaCharanChhandogi  please assign me this issue.

**Comment by MadhurimaNayak** [comment]
hey @prajwaln07 issue #20 addresses the same.

**Comment by prajwaln07** [comment]
@MadhurimaNayak  go ahead.
