### ISSUE TITLE
Templates for contributing 

### ISSUE THREAD

**Issue by Mehak-Mattoo** [BamaCharanChhandogi/READMEasy#33]
Adding templates for open source contributions like bug report, new issue suggestion helps in making issues regular and easy to track.

Could you assign this issue to me under hacktoberfest - accepted and gssoc 24-exrd. Thanks

**Comment by isha-dubey** [comment]
I would like to contribute to this repository by adding templates for:

Bug Reports
Feature Requests

These templates will help in streamlining the process of reporting issues, making them easier to track and maintain.

Could you kindly assign this issue to me under Hacktoberfest?
