### ISSUE TITLE
Search Query Only Displaying in Console

### ISSUE THREAD

**Issue by RaiDevX8** [BamaCharanChhandogi/READMEasy#34]
![Screenshot 2024-10-05 095929](https://github.com/user-attachments/assets/51f41f20-d272-463f-a33c-b477b481114b)
@BamaCharanChhandogi  
When a search is performed, the query is logged to the browser console
Expected Behavior:
  1) The search query should be used to display relevant results or trigger a search feedback message on the UI (e.g., "No results found" 
      or a list of search results).
2)The query should not just be logged to the console.

**Comment by BamaCharanChhandogi** [comment]
#spam
