### ISSUE TITLE
Website's navbar is not responsive for smartphone.

### ISSUE THREAD

**Issue by Nvntdad** [BamaCharanChhandogi/READMEasy#4]
the website is not responsive, i want to improve the responsive design of the website.
please assign this task to me under the contribution of GSSoC' 24.
![aa](https://github.com/user-attachments/assets/4e146c37-9a88-42cf-a8ca-10e1a5875b07)

**Comment by itznayan** [comment]
i will like to work on this issue .here is link of responsive navbar for mobile : https://drive.google.com/file/d/1iqDTn9z2nsVdKmp6tQ3FeGcLRPlJ7Ja6/view?usp=drive_link
