### ISSUE TITLE
Add Smooth and attractive transition on buttons

### ISSUE THREAD

**Issue by iamsohelx** [BamaCharanChhandogi/READMEasy#40]
![newbtn](https://github.com/user-attachments/assets/a23f47b3-8c4a-4fb4-8d4c-7da5bd47e077)
@BamaCharanChhandogi We Can improve the user experiance by adding smooth transition to buttons

**Comment by iamsohelx** [comment]
Hey @BamaCharanChhandogi i can help you to do this, could you please assign this task to me.

**Comment by BamaCharanChhandogi** [comment]
Do not need
