### ISSUE TITLE
 Unnecessary re-renders

### ISSUE THREAD

**Issue by devanshar** [BamaCharanChhandogi/READMEasy#5]
The NavLink components needs to be optimized as in your navigation can lead to re-renders. If the parent component re-renders, all child components, including navigation links, will also re-render.

**Comment by devanshar** [comment]
Hello @BamaCharanChhandogi assign this issue to me under hacktoberfest and gssoc 24

**Comment by Raj-Aditya-27** [comment]
Hi @BamaCharanChhandogi 
I can see that the works has not done yet.
So can you please assign it to me?
I will do it shortly

**Comment by devanshar** [comment]
> Hi @BamaCharanChhandogi I can see that the works has not done yet. So can you please assign it to me? I will do it shortly

this issue was already resolved
