### ISSUE TITLE
Dark mode light mode toggle

### ISSUE THREAD

**Issue by aditya07389** [BamaCharanChhandogi/READMEasy#51]
hey i just noticed your website does not have a light mode , i could add a toggle button which toggles between the two modes up to your navbar 

somewhere here :

![image](https://github.com/user-attachments/assets/c2658f6a-7498-444b-82de-62758fdfa8ab)

btw 
your website is really useful , i just used it for generating readme file for my project

**Comment by BamaCharanChhandogi** [comment]
#8
