### ISSUE TITLE
Adding star and fork this repo feature on the website

### ISSUE THREAD

**Issue by c4dr-me** [BamaCharanChhandogi/READMEasy#68]
I want to add the star and fork feature which will fetch the number of star and fork this repo have had and clicking them redirects to this repo

please assign the issue to me under gsoc and hacktoberfest

**Comment by c4dr-me** [comment]
i can add icons library and necessary packages, right? also can u add hacktoberfest label as well

**Comment by BamaCharanChhandogi** [comment]
> i can add icons library and necessary packages, right? also can u add hacktoberfest label as well

Yeah, you can use no problem.
