### ISSUE TITLE
Create Landing Page for README Generator with CSS styling (in both dark and light theme)

### ISSUE THREAD

**Issue by mansiruhil13** [BamaCharanChhandogi/READMEasy#79]
created landing page 
with proper css styling, in which add readme generator and profile generator with toggle key for dark theme also. 
![Screenshot 2024-10-15 215023](https://github.com/user-attachments/assets/b4626182-c9eb-49a0-bd5a-e4a2294dac59)

**Comment by mansiruhil13** [comment]
can you assign me under gssoc-ext and hacktoberfest please?

**Comment by BamaCharanChhandogi** [comment]
Duplicate
