### ISSUE TITLE
ADD Footer and dynamic copyright

### ISSUE THREAD

**Issue by AE-Hertz** [BamaCharanChhandogi/READMEasy#86]
add a footer and dynamic copyright year. We can make it "dynamic copyright" or "dynamic copyright notice." It will ensure that the copyright year is automatically updated to reflect the current year, enhancing user experience and accuracy.

Please assign me with this issue under gssoc-ext level 3 and hacktoberfest'24

**Comment by BamaCharanChhandogi** [comment]
Do not need
