### ISSUE TITLE
[Custom]: CI-CD Workflow

### ISSUE THREAD

**Issue by harshbhar0629** [BamaCharanChhandogi/READMEasy#95]
# 💡 Custom Issue

### 📝 Description
There is no CI-CD Workflow in this repo.

What CI-CD did??
A CI/CD workflow on GitHub automates the process of building, testing, and deploying code. When changes are pushed to the repository, GitHub Actions triggers the workflow, starting with building the code, running tests, and performing quality checks. If the tests pass, the code can be deployed to a staging or production environment. Notifications are sent to inform stakeholders about the workflow's success or failure.

### 🔍 Steps to Reproduce (if applicable)
1. Go to .github folder  
2. Make separate file for CI-CD workflow

### 🎯 Expected Outcome
When user try to create a PR then it run and check first all test case.

@BamaCharanChhandogi Please assign this issue to me under gssoc-ext, level-2,3:)

**Comment by Harshithaa17** [comment]
I would like to work on this issue

**Comment by harshbhar0629** [comment]
> I would like to work on this issue

No i will make PR today

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi This is my issue..so please merge my PR:)
